server:
  port: 8002
spring:
  application:
    name: GLYDL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.216.13:3306/yqfk?serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 120.27.216.13
aliyun:
  sms:
    accessKeyId: LTAI4G4LyM5SwtQBKjcijas2
    accessKeySecret: nanXZMVYbwiW26nWOHBPLeF25QpmhW
    sign_name: QST2020
    template_code: SMS_203717866
